# Generated by Django 4.1.4 on 2022-12-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Name')),
                ('desc', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(default='default.png', upload_to='home_images', verbose_name='image')),
                ('price', models.CharField(max_length=120, verbose_name='Price')),
            ],
        ),
    ]
